package dev.henkle.korvus.types

import kotlinx.serialization.json.JsonElement

/**
 * A scope for executing batch commands to the RavenDB
 */
interface TypedBatchCommandScope<T: Any> {
    /**
     * Inserts [document] into the database if it doesn't exist, or updates the existing document in the database
     * if it does exist.
     *
     * @param document the document to write to the database
     * @param id the id to use for the document. The database will automatically generate the id
     * if this is set to an empty string
     * @param changeVector the change vector for the document or null if a change vector is not being used
     *
     * @return a result that indicates success when the update succeeded or failure otherwise
     *
     * @see dev.henkle.korvus.ext.put
     */
    suspend fun put(document: T, id: String, changeVector: String? = null)

    /**
     * Inserts the [documents] into the database if they do not exist, or updates the existing documents in the
     * database if they do exist.
     *
     * @param documents the list of documents to write to the database
     * @param ids the optional ids to use for [documents]. If an empty string, the id will be generated by the database
     * @param changeVectors the change vectors for the ids. There should be on entry in the change vectors list for each
     * id in [ids] OR an empty list if no change vectors are being provided
     *
     * @return a result that indicates success when all database operations succeeded or failure otherwise
     *
     * @see dev.henkle.korvus.ext.put
     */
    suspend fun put(
        documents: Collection<T>,
        ids: Collection<String>,
        changeVectors: Collection<String?> = emptyList(),
    )

    /**
     * Deletes a document from the database.
     *
     * @param id the id of the document to delete
     * @param changeVector the change vector for the document or null if a change vector is not being used
     */
    suspend fun delete(id: String, changeVector: String? = null)

    /**
     * Deletes documents from the database.
     *
     * @param ids the ids of the documents to delete
     * @param changeVectors the change vectors for the ids. There should be on entry in the change vectors list for each
     * id in [ids] OR an empty list if no change vectors are being provided
     */
    suspend fun delete(ids: Collection<String>, changeVectors: Collection<String?> = emptyList())

    /**
     * Deletes documents from the database whose ids share the provided prefix.
     *
     * @param prefix the prefix of the ids to delete
     */
    suspend fun deleteByIDPrefix(prefix: String)

    /**
     * Patches a document in the database.
     *
     * @param id the id of the document to patch
     * @param patchScript the JavaScript script that will be used to patch the document. Named arguments can be created
     * by prefixing the argument name with '$' e.g. "this.name = $name"
     * @param arguments the arguments for the [patchScript]. The leading '$' should be excluded. All values should be
     * serializable as [JsonElement]s
     * @param changeVector the change vector for the document or null if a change vector is not being used
     */
    suspend fun patch(
        id: String,
        patchScript: String,
        arguments: Map<String, Any?> = emptyMap(),
        changeVector: String? = null,
    )

    /**
     * Patches documents in the database.
     *
     * @param ids the ids of the documents to patch
     * @param patchScripts the JavaScript scripts that will be used to patch the documents. There should be one patch
     * script for each id in [ids]. Named arguments can be created by prefixing the argument name with '$' e.g.
     * "this.name = $name"
     * @param arguments the arguments for the [patchScripts]. The leading '$' should be excluded. All values should be
     * serializable as [JsonElement]s. There should be one entry arguments list for each id in [ids] OR an empty list if
     * no arguments are needed for any of the scripts
     * @param changeVectors the change vectors for the ids. There should be on entry in the change vectors list for each
     * id in [ids] OR an empty list if no change vectors are being provided
     */
    suspend fun patch(
        ids: Collection<String>,
        patchScripts: Collection<String>,
        arguments: Collection<Map<String, Any?>> = emptyList(),
        changeVectors: Collection<String?> = emptyList(),
    )

    /**
     * Patches documents in the database.
     *
     * @param ids the ids of the documents to patch
     * @param patchScript the JavaScript script that will be used to patch the documents. Named arguments can be created
     * by prefixing the argument name with '$' e.g. "this.name = $name"
     * @param arguments the arguments for the [patchScript]. The leading '$' should be excluded. All values should be
     * serializable as [JsonElement]s. There should be one entry in the arguments list for each id in [ids] OR an empty
     * list if no arguments are needed for any of the scripts
     * @param changeVectors the change vectors for the ids. There should be on entry in the change vectors list for each
     * id in [ids] OR an empty list if no change vectors are being provided
     */
    suspend fun patch(
        ids: Collection<String>,
        patchScript: String,
        arguments: Collection<Map<String, Any?>> = emptyList(),
        changeVectors: Collection<String?> = emptyList(),
    )
}
