name: CI

on:
  push:
    branches: [master]
    paths:
      - "**/*.kt"
      - "**/*.kts"
      - "**/jni/*"
      - gradle/**
  pull_request:

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref_name}}

permissions:
  contents: write

defaults:
  run:
    working-directory: ./kotlin-tree-sitter

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate grammar files
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
          cache-dependency-path: |
            gradle/libs.versions.toml
            gradle/wrapper/gradle-wrapper.properties
      - name: Cache Kotlin/Native prebuilt
        uses: actions/cache@v4
        with:
          path: ${{runner.tool_cache}}/konan/kotlin-native-prebuilt-*
          key: konan-${{runner.os}}-prebuilt-2.0
      - name: Generate files
        run: ./gradlew --no-daemon generateGrammarFiles
        env:
          KONAN_DATA_DIR: ${{runner.tool_cache}}/konan
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-files
          path: kotlin-tree-sitter/languages/*/build/generated/**
          retention-days: 1
  build-libs:
    runs-on: ${{matrix.os}}
    name: Build ${{matrix.platform}}-${{matrix.arch}} library
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
            lib: libktreesitter.so
            cmake_args: >-
              -DCMAKE_BUILD_TYPE=RelWithDebugInfo
          - os: ubuntu-latest
            platform: linux
            arch: aarch64
            lib: libktreesitter.so
            cmake_args: >-
              -DCMAKE_BUILD_TYPE=RelWithDebugInfo
              -DCMAKE_SYSTEM_PROCESSOR=aarch64
              -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc
              -DCMAKE_FIND_ROOT_PATH=/usr/aarch64-linux-gnu
          - os: windows-latest
            platform: windows
            arch: x64
            lib: ktreesitter.dll
          - os: macos-latest
            platform: macos
            arch: x64
            lib: libktreesitter.dylib
            cmake_args: >-
              -DCMAKE_BUILD_TYPE=RelWithDebugInfo
              -DCMAKE_OSX_ARCHITECTURES=x86_64
          - os: macos-latest
            platform: macos
            arch: aarch64
            lib: libktreesitter.dylib
            cmake_args: >-
              -DCMAKE_OSX_ARCHITECTURES=arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          architecture: ${{matrix.arch}}
      - name: Set up cross compilation
        run: sudo apt-get install -qy {binutils,gcc}-aarch64-linux-gnu
        if: runner.os == 'Linux' && matrix.arch == 'aarch64'
      - name: Configure CMake
        working-directory: ktreesitter
        run: >-
          cmake -B .cmake/build ${{matrix.cmake_args}}
          -DCMAKE_INSTALL_LIBDIR=lib/${{matrix.platform}}/${{matrix.arch}}
          -DCMAKE_INSTALL_BINDIR=lib/${{matrix.platform}}/${{matrix.arch}}
      - name: Build JNI library
        working-directory: ktreesitter
        run: |-
          cmake --build .cmake/build --config Release
          cmake --install .cmake/build --config Release --prefix .cmake/build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ktreesitter-lib-${{matrix.platform}}-${{matrix.arch}}
          path: ./kotlin-tree-sitter/ktreesitter/.cmake/build/lib/**
          retention-days: 2
  build-jars:
    runs-on: ${{matrix.os}}
    name: Build ${{matrix.platform}} packages
    needs: [build-libs]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: common
            targets: >-
              generateGrammarFiles
              :ktreesitter:publishKotlinMultiplatformPublicationToReposiliteRepository
          - os: ubuntu-latest
            platform: JVM
            targets: >-
              :ktreesitter:publishJvmPublicationToReposiliteRepository
          - os: ubuntu-latest
            platform: Android
            targets: >-
              :ktreesitter:publishAndroidReleasePublicationToReposiliteRepository
          - os: ubuntu-latest
            platform: Linux
            targets: >-
              generateGrammarFiles
              :ktreesitter:publishLinuxX64PublicationToReposiliteRepository
              :ktreesitter:publishLinuxArm64PublicationToReposiliteRepository
          - os: windows-latest
            platform: Windows
            targets: >-
              generateGrammarFiles
              :ktreesitter:publishMingwX64PublicationToReposiliteRepository
          - os: macos-latest
            platform: macOS/iOS
            targets: >-
              generateGrammarFiles
              :ktreesitter:publishMacosX64PublicationToReposiliteRepository
              :ktreesitter:publishMacosArm64PublicationToReposiliteRepository
              :ktreesitter:publishIosArm64PublicationToReposiliteRepository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
          cache-dependency-path: |
            kotlin-tree-sitter/gradle/libs.versions.toml
            kotlin-tree-sitter/gradle/wrapper/gradle-wrapper.properties
      - name: Set up cross compilation
        run: sudo apt-get install -qy {binutils,gcc}-aarch64-linux-gnu
        if: matrix.platform == 'Linux' || matrix.platform == 'common'
      - name: Restore Kotlin/Native prebuilt
        uses: actions/cache/restore@v4
        with:
          path: ${{runner.tool_cache}}/konan/kotlin-native-prebuilt-*
          key: konan-${{runner.os}}-prebuilt-2.0
      - name: Restore Kotlin/Native dependencies
        uses: actions/cache/restore@v4
        if: matrix.platform != 'JVM' && matrix.platform != 'Android'
        with:
          path: ${{runner.tool_cache}}/konan/dependencies
          key: konan-${{runner.os}}-dependencies
      - name: Download library artifacts
        uses: actions/download-artifact@v4
        if: matrix.platform == 'JVM'
        with:
          path: kotlin-tree-sitter/ktreesitter/src/jvmMain/resources/lib
          pattern: ktreesitter-lib-*
          merge-multiple: true
      - name: Build packages
        run: ./gradlew --no-daemon ${{matrix.targets}}
        env:
          KONAN_DATA_DIR: ${{runner.tool_cache}}/konan
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ktreesitter-jars-${{matrix.platform == 'macOS/iOS' && 'macOS-iOS' || matrix.platform}}
          path: |
            kotlin-tree-sitter/ktreesitter/build/repo/**
            !kotlin-tree-sitter/ktreesitter/build/repo/**/maven-metadata.*
          retention-days: 2
